services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nathan
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d notes"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./project
      dockerfile: Dockerfile
    container_name: notes-app
    ports:
      - "8000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/notes
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: nathan
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: node:25.2.1
    container_name: notes-front
    working_dir: /app
    volumes:
      - ./note-front:/app
      - node_modules:/app/node_modules
    command: >
      sh -c "
        npm ci --include=dev --ignore-scripts &&
        npm run build &&                           
        npx serve -s dist -l 80
      "
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
    env_file:
      - ./note-front/.env.production
    depends_on:
      - backend

volumes:
  db_data:
  node_modules:      # ‚Üê cette ligne manquait